name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Меняем на 3.11
          cache: 'pip'


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Стабильная версия для Flet 0.21.0
          channel: 'stable'

      - name: Install Flet CLI
        run: |
          pip install flet==0.23.2

      - name: Flet Build APK
        run: |
          pip install flet==0.23.2
          
          # 1. Находим, куда flet скачал архив (обычно это /tmp)
          # 2. Создаем фейковую папку, которую он хочет, на основе системного Python
          # Это предотвратит запуск внутреннего процесса распаковки
          
          export HOST_PYTHON_DIR=$(ls -d /tmp/hostpython3.11_* 2>/dev/null || echo "/tmp/hostpython3.11_FIXED")
          mkdir -p $HOST_PYTHON_DIR
          cp -R /opt/hostedtoolcache/Python/3.11.*/x64/* $HOST_PYTHON_DIR/ || true
          
          # 3. Запуск сборки с отключенным обновлением дистрибутива
          flet build apk --verbose


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-crypto-app
          path: build/apk/*.apk

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y setuptools
          
