name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Именно в кавычках и без патч-версии
          cache: 'pip'
          update-environment: true


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Стабильная версия для Flet 0.21.0
          channel: 'stable'

      - name: Install Flet CLI
        run: |
          pip install flet==0.21.2

      - name: Flet Build APK
        run: |
          # Принудительно удаляем возможные битые остатки прошлых запусков
          rm -rf /tmp/hostpython*
          rm -rf /tmp/cpython*
          
          # Запускаем сборку с максимальным логированием
          flet build apk --verbose


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-crypto-app
          path: build/apk/*.apk

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y setuptools
          
