name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Меняем на 3.11
          cache: 'pip'


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Стабильная версия для Flet 0.21.0
          channel: 'stable'

      - name: Install Flet CLI
        run: |
          pip install flet==0.21.2

      - name: Flet Build APK
        run: |
          # 1. Сначала ставим flet, чтобы он скачал свой архив, если его нет
          pip install flet==0.21.2
          
          # 2. Магия: вручную создаем папку и распаковываем архив
          # Это предотвратит зависание самого flet
          mkdir -p /tmp/hostpython3.11_OSWBHU
          tar -xzf /tmp/cpython-3.11.6+20231002-x86_64-unknown-linux-gnu-install_only.tar.gz -C /tmp/hostpython3.11_OSWBHU || true
          
          # 3. Запускаем сборку
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-crypto-app
          path: build/apk/*.apk

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y setuptools
          
