name: Build Android APK
on: [push] # Собирать каждый раз, когда ты обновляешь код

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Flet and Build
        run: |
          pip install flet
          flet build apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: build/apk/*.apk
